apiVersion: v1

kind: Service

metadata:
  name: k8s-simple-service

spec:
  selector:
    app: k8s-simple-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer